### PR TITLE
Updated ts-node dependency and README

### PR DESCRIPTION
**Pull request by GeeWee**
I updated the Readme to describe what this plugin does and what it doesn't, and I upgraded the version of ts-node to the newest.

I've tested the new version of ts-node and it works just fine - no breaking changes.

### CODE REVIEW

**Review by wzrdtales — CHANGES_REQUESTED** [review]
Don't commit the yarn.lock file, maybe add it to .gitignore as well

**Comment by GeeWee** [comment]
Are you sure? I can remove it, but the yarn.lock file is [meant to be committed](https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for)

**Comment by wzrdtales** [comment]
Please also note although, I mentioned this in several other issues today, so maybe you already noticed. For the next 2 weeks I will only sporadically react to requests, as I am head deep into working on slides for the conference. As soon as this is over I will reach out to everyone that had question while that period of time.

**Comment by wzrdtales** [comment]
Yes I am sure, first I do not **yet** consider yarn to be a major tool used by the masses and it is actually the same like the new package-lock.json which I would rather allow than the yarn.lock. Actually I don't like either one of those, for the reason that they screw up *all* pull requests with conflicts that are no conflicts real conflicts. i know that there is some option to handle them as binary instead, but not looked at that option yet though.

**Comment by GeeWee** [comment]
That's fair enough. Have a good conference.

I've removed the yarn.lock

**Comment by wzrdtales** [comment]
Thanks, btw. I tried yarn once and needed to throw it away again b/c it screwed up the whole CI toolchain. For some reason it was completely unable to handle some of the natively compiled stuff in the dependencies. Maybe they fixed that by now, but haven't tried again, But actually npm improved a lot in version 5 which introduced many of the same features that made yarn superior before. So haven't made a new comparison of both, so I can just make an educated guess that the difference is not so big anymore, so I am not strictly against yarn, but also not yet a supporter :)

**Review by wzrdtales — APPROVED** [review]

**Comment by GeeWee** [comment]
Yeah I definitely think that npm stepped up its game with the package-lock as well. I mostly switched because yarn is *a lot* faster - but maybe npm 5 got some nice improvements there as well. :)

**Comment by wzrdtales** [comment]
That it is faster was the reason I initially tried it just to get disappointed that it does not work like intended and walk away again :joy: .

**Pull request merged**
